#!/bin/bash
#NAMESPACE=view_main

dependencies::depends "gpscalc/haversine"
dependencies::depends "redis/redis"
dependencies::depends "http/webauth"

function name() {
    local name=`http::get_post "name" | sed 's/[^a-zA-Z0-9.,:;!?@~#$%^&*()+-]//g'`
    if [[ ! -z $name ]]; then
        redis::setex "`webauth::getid`-name" "$name" 28800
    fi

    if [[ $(redis::get "`webauth::getid`-name") == "" ]]; then
        cat << HTMLCODE
            <form method=post>
                <input type="text" name="name" /><input type=submit value="yourname [ASCII PLOX]"/>
            </form>
HTMLCODE
    else
        redis::get "`webauth::getid`-name"
    fi
}

function show() {
cat << HTMLCODE
    <html>
    <head>
        <title>hello.jpg</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style type=text/css>
            #map {
                height:500px;
                width:500px;
            }
        </style>
         <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
           integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
           crossorigin=""/>
          <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    </head>
    <body style="font-family: monospace;">
        <h1>Hi `this::name`! </h1>
        <table border=1>
        <tr>
        <th>Location&nbsp;data</th>
        <th>Hint</th>
        <th>Map</th>
        </tr>
        <tr>
        <td>
        <p>current location at <span id='position'></span></p>
        <p>distance: <span id='distance'></span> meters</p>
        <p>bearing: <span id='bearing'></span> degrees (0=N, 90=E ...)</p>
        </td>
        <td>
        <div id="hint">
            HINT
        </div>
        </td>
        <td>
        <div id="map">

        </div>
        </td>
        </tr><tr>
        <td colspan=3><form method="post" action="/?route=solve">
                                  <input type="text" name="solution_key"/> <input type="submit" value="submit solution key" />
                              </form>
                              </td>
        </tr>
        </table>
        <script type="application/javascript" src="scripts.js">

        </script>
    </body>
</html>
HTMLCODE
}
